version: "3"

services:
  jenkins:
    build: ./jenkins
    container_name: ci-jenkins
    ports:
      - "8181:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
  registry:
    image: registry:2
    container_name: ci-registry
    ports:
      - "5000:5000"

volumes:
  jenkins-data:
  jenkins-docker-certs:
