version: "3"

services:
  grafana:
    image: grafana/grafana-oss
    depends_on:
      - influxdb-18
    ports:
      - "3000:3000"
    volumes:
      # Run from the root of the repo otherwise this path will not work and you will not see pre-provisioned dashboard
      - "./k6/grafana/dashboards:/etc/grafana/provisioning/dashboards/"
      - "./k6/grafana/datasources:/etc/grafana/provisioning/datasources/"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false

  influxdb-18:
    image: influxdb:1.8
    ports:
      - "8087:8086"
    volumes:
      - "influxdb18:/var/lib/influxdb"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=infludadmin
      - INFLUXDB_ADMIN_PASSWORD=influxdbpassword
      - INFLUXDB_USER=influxdbuser
      - INFLUXDB_USER_PASSWORD=influxdbuserpassword

  # influxdb:
  #   image: influxdb:2.0
  #   ports:
  #     - "8086:8086"
  #   volumes:
  #     - "influxdb2:/var/lib/influxdb2"
  #   environment:
  #     - DOCKER_INFLUXDB_INIT_MODE=setup
  #     - DOCKER_INFLUXDB_INIT_USERNAME=my-user
  #     - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
  #     - DOCKER_INFLUXDB_INIT_ORG=my-org
  #     - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
  #     - DOCKER_INFLUXDB_INIT_RETENTION=1w
  #     - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token

volumes:
  # influxdb2:
  influxdb18: