jobs:
  - script: >
      folder('test_jobs_k6')
  - script: >
      pipelineJob('test_jobs_k6/run_load_k6_tests') {
        description('Runs k6 load tests. In order to view results in grafana, first raise grafana+influxdb stack')
        definition {
          cps {
            script("""\
                pipeline {
                  agent any
                  stages {
                    stage('checkout') {
                      steps {
                        cleanWs()

                        git url: 'https://github.com/andreav/jenkins-docker-qa.git'
                      }
                    }

                    stage('running Load tests') {
                      agent { 
                        docker { 
                          image 'loadimpact/k6' 
                          reuseNode true
                          // This image is not interactive and is designed for running k6 and exiting immedeately
                          // Make it interactive and remove k6 entrypoint
                          // refs - https://stackoverflow.com/questions/52558150/jenkins-pipeline-docker-container-is-not-running
                          args "-i --entrypoint="
                        } 
                      }			
                      steps {
                        sh 'k6 run -e K6_TEST_RESULTS_HTML_FULL_FILE_PATH="./k6-test.results.html" --out json=./k6-test-results.json ./k6/load_tests.js'
                      }
                    }

                  }
                }""".stripIndent())
              }
            }
          }              
