jobs:
  - script: >
      folder('test_jobs_qa')
  - script: >
      pipelineJob('test_jobs_qa/qa-pitstop-pipeline') {
        description('An example from a github repo for QA')
        definition {
          cps {
            script("""\
                pipeline {
                  agent any
                  stages {
                    stage('checkout') {
                      steps {
                        cleanWs()

                        checkout([
                          \$class: 'GitSCM', 
                          branches: [[name: '*/master']], 
                          extensions: [], 
                          userRemoteConfigs: [[url: 'https://github.com/andreav/pitstop']]
                        ])
                      }
                    }

                    stage('sonarscanner') {
                      environment {
                        DOTNET_CLI_HOME = "/tmp/DOTNET_CLI_HOME"
                        SONARQUBE_PROJECT_NAME="testproject"
                        SONARQUBE_URL="http://host.docker.internal:9000"
                        SONARQUBE_LOGIN="7aa774b870de5d12f3677dc28a154ffedfc2925b"
                      }
                      agent { 
                        docker { 
                          image 'mcr.microsoft.com/dotnet/sdk:5.0' 
                          reuseNode true
                          args '''
                                  -u root
                                  -e PATH="\$PATH:/tmp/DOTNET_CLI_HOME/.dotnet/tools"
                                '''            
                        } 
                      }			
                      steps {
                        // Prerequisites
                        sh "apt-get update && apt-get install -y default-jre"
                        sh "dotnet tool install --global dotnet-sonarscanner"  
                          
                        dir("./src/") {
                            sh "dotnet sonarscanner begin /k:\$SONARQUBE_PROJECT_NAME /d:sonar.host.url=\$SONARQUBE_URL  /d:sonar.login=\$SONARQUBE_LOGIN"
                            sh "dotnet build pitstop.sln"
                            sh "dotnet sonarscanner end /d:sonar.login=\$SONARQUBE_LOGIN"
                        }
                      }
                    }

                    stage('unit tests') {
                      environment {
                        DOTNET_CLI_HOME = "/tmp/DOTNET_CLI_HOME"
                      }
                      agent { 
                        docker { 
                            image 'mcr.microsoft.com/dotnet/sdk:5.0' 
                            reuseNode true
                        } 
                      }			
                      steps {
                        dir("./src/WorkshopManagement.UnitTests") {
                            sh "dotnet test . --logger:trx --results-directory ./TestResults /p:CollectCoverage=true /p:CoverletOutput=./TestResults/ /p:CoverletOutputFormat=cobertura%2Copencover%2Cjson"
                        }                        

                        // with plugin xUnit
                        xunit([
                            MSTest(
                                deleteOutputFiles: false,
                                failIfNotNew: true,
                                pattern: '**/*.trx',
                                skipNoTestFiles: false,
                                stopProcessingIfError: true
                            )
                        ])

                        // with mstest plugin
                        //mstest failOnError: false
                        
                        cobertura autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: '**/*cobertura.xml', conditionalCoverageTargets: '70, 0, 0', failUnhealthy: false, failUnstable: false, lineCoverageTargets: '80, 0, 0', maxNumberOfBuilds: 0, methodCoverageTargets: '80, 0, 0', onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false
                      }
                    }    
                  }                
                }""".stripIndent())
              }
            }
          }          
