jobs:
  - script: >
      folder('test_jobs_selenium')
  - script: >
      pipelineJob('test_jobs_selenium/run_ui_tests_against_basic_grid') {
        description('Runs a selenium grid with 3 browsers and run tests against that grid')
        definition {
          cps {
            script("""\
                pipeline {
                  agent any
                  stages {
                    stage('checkout') {
                      steps {
                        cleanWs()

                        dir('sut') {
                            git url: 'https://github.com/andreav/pitstop'
                        }
                        dir('ci') {
                            git url: 'https://github.com/andreav/jenkins-docker-qa.git'
                        }
                      }
                    }

                    stage('setting up selenium grid') {
                      steps {
                        sh "docker-compose -p seleniumgrid-\$BUILD_NUMBER -f ./ci/selenium/docker-compose.yml up -d"
                        sh 'chmod +x ./ci/selenium/wait-for-grid.sh'
                        sh './ci/selenium/wait-for-grid.sh'                        
                      }
                    }

                    stage('running UI tests') {
                      environment {
                        DOTNET_CLI_HOME = "/tmp/DOTNET_CLI_HOME"
                        XDG_DATA_HOME = "/tmp/DOTNET_CLI_HOME"
                        SELENIUM_HUB_ADDRESS = "http://host.docker.internal:4444"
                      }
                      agent { 
                        docker { 
                          image 'mcr.microsoft.com/dotnet/sdk:6.0' 
                          reuseNode true
                        } 
                      }			
                      steps {
                        // should run sut & sut tests .. now just run a demo UI test here
                        sh 'dotnet test ./ci/selenium/xunit-selenium-tests'
                      }
                    }    
                  }
                  post {
                    cleanup {
                        sh "docker-compose -p seleniumgrid-\$BUILD_NUMBER -f ./ci/selenium/docker-compose.yml down -v"
                    }
                  }   
                }""".stripIndent())
              }
            }
          }              
